note: None
seed: 123
num_gpus: 2
num_epochs: 80
checkpoint_dir: ckpt
resume_dir: ckpt

train_hyp:
  instance_param_threshold: 0.5
  bandwidth: 5

solver:
  method: adam
  lr: 0.0002
  lr_dynamic_decay: True
  lr_decay_rate: 0.5
  lr_decay_epoch: 60
  lr_decay_interval: 20
  weight_decay: 0.0001

dataset:
  root_dir:
  batch_size: 32
  num_workers: 8
  h: 192
  w: 256
  num_class: 7

model:
  arch: resnet101
  pretrained: True



